//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estat.Sri.MappingStore.Store.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estat.Sri.MappingStore.Store.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported..
        /// </summary>
        internal static string ErrorNotSupported {
            get {
                return ResourceManager.GetString("ErrorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine parent.
        /// </summary>
        internal static string ExceptionCannotDetermineParent {
            get {
                return ResourceManager.GetString("ExceptionCannotDetermineParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PRIMARY KEY value provided..
        /// </summary>
        internal static string ExceptionInvalidPrimaryKey {
            get {
                return ResourceManager.GetString("ExceptionInvalidPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Component structure types are supported..
        /// </summary>
        internal static string ExceptionNotComponentType {
            get {
                return ResourceManager.GetString("ExceptionNotComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not identifiable structure type provided..
        /// </summary>
        internal static string ExceptionNotIdentifiable {
            get {
                return ResourceManager.GetString("ExceptionNotIdentifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported attachment level..
        /// </summary>
        internal static string ExceptionUnsupportedAttachmentLevel_ {
            get {
                return ResourceManager.GetString("ExceptionUnsupportedAttachmentLevel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to an unsupported structure: {0}.
        /// </summary>
        internal static string ExceptionUnsupportedStructureReferenceFormat1 {
            get {
                return ResourceManager.GetString("ExceptionUnsupportedStructureReferenceFormat1", resourceCulture);
            }
        }
    }
}
